[build]
  publish = "public"
  functions = "netlify/functions"
  command = "npm install"

[functions]
  node_bundler = "esbuild"
  included_files = ["node_modules/@netlify/blobs/**"]

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
